"""Role profiles: per-member instructions and skills for hired agents.

A profile is a folder in the project, `.orchestra/roles/<profile>/`:

    ROLE.md                     the member's own instructions
    .claude/skills/<skill>/     skills only this role gets (optional)
    CLAUDE.md                   optional extra memory, loaded via --add-dir

For a Claude member, `hire` turns the profile into:

- a session agent `.claude/agents/horchestra-<role>.md` whose body holds the
  team context, ROLE.md, and the skills it must use. `claude --resume` keeps
  the agent, so these instructions survive a Herdr restart.
- `--add-dir <profile folder>` so the role-only skills (and CLAUDE.md) load.
- a `--settings` file denying unwanted skills (`Skill(<pattern>)`). Denied
  skills cannot be used, but Claude Code still lists them.

`only_skills` is an allowlist: the agent's instructions say to use only those
skills (plus the role's own), and every other skill found on disk (user and
project `.claude/skills`) is denied. Skills from Claude Code plugins and
built-ins are not on disk where we can list them, so for those only the
instruction applies.

Herdr resumes agents with a plain `claude --resume`, which reuses the system
prompt recorded when the conversation began and drops these flags, so the
startup hook respawns profile members (`claude --resume <id>
--system-prompt-snapshot off` plus the flags) to re-apply them.
"""

import json
import os
import re

ROLES_DIR = os.path.join(".orchestra", "roles")
AGENT_PREFIX = "horchestra-"
GENERATED_MARK = "<!-- generated by horchestra from {source}; edit that file, not this one -->"
LEGACY_PREFIX = "orchestra-"  # pre-0.1 generated agent names


class RoleError(Exception):
    pass


class Profile:
    """Everything a member's launch needs, resolved from team.toml + disk."""

    def __init__(self, role, name, folder, text, own_skills, uses, deny, only=None, auto_deny=()):
        self.only = only  # allowlist (None = no allowlist)
        self.auto_deny = list(auto_deny)  # on-disk skills outside the allowlist
        self.role = role
        self.name = name  # profile folder name, or None
        self.folder = folder  # absolute path, or None
        self.text = text  # ROLE.md content ('' if none)
        self.own_skills = own_skills  # skill names inside the profile folder
        self.uses = uses
        self.deny = deny

    def summary(self):
        """Short human line, e.g. 'slides · 2 own skills · uses slide-kit'."""
        parts = [self.name or "no profile"]
        if self.own_skills:
            parts.append(f"{len(self.own_skills)} own skill{'s' * (len(self.own_skills) != 1)}")
        if self.only is not None:
            parts.append(f"only {len(self.allowed)} skill{'s' * (len(self.allowed) != 1)}")
        elif self.uses:
            parts.append("uses " + ", ".join(self.uses))
        if self.deny or self.auto_deny:
            parts.append(f"denies {len(self.all_denied)}")
        return " · ".join(parts)

    @property
    def allowed(self):
        """Skills the member is told to use (allowlist, or just the ones to use)."""
        names = list(self.only or []) + list(self.uses) + list(self.own_skills)
        return list(dict.fromkeys(names))

    @property
    def all_denied(self):
        return list(dict.fromkeys(self.deny + self.auto_deny))

    @property
    def is_empty(self):
        return not (self.text or self.own_skills or self.uses or self.deny or self.only is not None)


def roles_root(team_root):
    return os.path.join(team_root, ROLES_DIR)


def skills_in(folder):
    skills_dir = os.path.join(folder, ".claude", "skills")
    if not os.path.isdir(skills_dir):
        return []
    return sorted(
        name for name in os.listdir(skills_dir)
        if os.path.isfile(os.path.join(skills_dir, name, "SKILL.md"))
    )


def skill_name(skill_dir):
    """A skill's `name:` from its SKILL.md frontmatter, else its folder name."""
    try:
        with open(os.path.join(skill_dir, "SKILL.md")) as fh:
            head = fh.read(4096)
    except OSError:
        return None
    match = re.match(r"---\s*\n(.*?)\n---", head, re.S)
    if match:
        name = re.search(r"^name:\s*['\"]?([^'\"\n]+?)['\"]?\s*$", match.group(1), re.M)
        if name:
            return name.group(1).strip()
    return os.path.basename(skill_dir)


def discover_skills(team_root, user_dir=None):
    """Skill names on disk: user (~/.claude/skills) and project .claude/skills."""
    user_dir = user_dir or os.path.expanduser("~/.claude/skills")
    found = []
    for base in (user_dir, os.path.join(team_root, ".claude", "skills")):
        if not os.path.isdir(base):
            continue
        for entry in sorted(os.listdir(base)):
            name = skill_name(os.path.join(base, entry))
            if name:
                found.append(name)
    return list(dict.fromkeys(found))


def list_profiles(team_root):
    root = roles_root(team_root)
    if not os.path.isdir(root):
        return []
    return sorted(
        name for name in os.listdir(root)
        if os.path.isdir(os.path.join(root, name)) and not name.startswith(".")
    )


def _strings(value, field):
    if value is None:
        return []
    if isinstance(value, str):
        value = [value]
    if not isinstance(value, list) or not all(isinstance(v, str) and v.strip() for v in value):
        raise RoleError(f"{field} must be a list of names")
    return [v.strip() for v in value]


def load(team_root, team, member, user_skills_dir=None):
    """Resolve a member's profile. `profile` defaults to the role's folder."""
    role = member["role"]
    explicit = member.get("profile")
    name = explicit or (role if os.path.isdir(os.path.join(roles_root(team_root), role)) else None)
    folder = text = None
    own = []
    if name:
        if not re.fullmatch(r"[A-Za-z0-9_.-]+", name) or name.startswith("."):
            raise RoleError(f"invalid profile name {name!r}")
        folder = os.path.join(roles_root(team_root), name)
        if not os.path.isdir(folder):
            raise RoleError(f"profile folder {os.path.relpath(folder, team_root)} does not exist")
        role_md = os.path.join(folder, "ROLE.md")
        if os.path.isfile(role_md):
            with open(role_md) as fh:
                text = fh.read().strip()
        own = skills_in(folder)
    deny = _strings(team.get("deny_skills"), "deny_skills") + _strings(member.get("deny_skills"), "deny_skills")
    uses = _strings(member.get("uses_skills"), "uses_skills")
    only = _strings(member.get("only_skills"), "only_skills") if "only_skills" in member else None
    wanted = uses + (only or [])
    blocked = [s for s in wanted if any(_glob_match(p, s) for p in deny)]
    if blocked:
        raise RoleError(f"{role}: skills both allowed and denied: {', '.join(blocked)}")
    auto_deny = []
    if only is not None:
        allowed = set(only) | set(uses) | set(own)
        auto_deny = [s for s in discover_skills(team_root, user_skills_dir) if s not in allowed]
    return Profile(role, name, folder, text or "", own, uses, list(dict.fromkeys(deny)),
                   only=only, auto_deny=auto_deny)


def _glob_match(pattern, name):
    return re.fullmatch(re.escape(pattern).replace(r"\*", ".*"), name) is not None


def agent_name(role):
    slug = re.sub(r"[^a-z0-9-]+", "-", role.lower()).strip("-") or "member"
    return AGENT_PREFIX + slug


def agent_body(profile, team_context):
    """The member's session-agent instructions."""
    parts = [team_context.strip()]
    if profile.text:
        parts.append(f"## Your role: {profile.role}\n\n{profile.text}")
    skills = profile.allowed
    if profile.only is not None:
        lines = "\n".join(f"- `{s}`" for s in skills) or "- (none)"
        parts.append(
            "## Skills for this role\n\nUse ONLY these skills (invoke them with the Skill "
            "tool) whenever the work touches their area. Do not invoke any other skill, "
            f"even if it is listed as available:\n{lines}"
        )
    elif skills:
        lines = "\n".join(f"- `{s}`" for s in skills)
        parts.append(
            "## Skills for this role\n\nUse these skills (invoke them with the Skill tool) "
            f"whenever the work touches their area; load them before you start:\n{lines}"
        )
    if profile.deny:
        parts.append("Do not use these skills: " + ", ".join(f"`{s}`" for s in profile.deny) + ".")
    return "\n\n".join(parts) + "\n"


def write_agent_file(team_root, profile, team_context):
    """Write `.claude/agents/horchestra-<role>.md`; returns the agent name."""
    name = agent_name(profile.role)
    agents_dir = os.path.join(team_root, ".claude", "agents")
    os.makedirs(agents_dir, exist_ok=True)
    source = (os.path.join(ROLES_DIR, profile.name, "ROLE.md") if profile.name else "team.toml")
    front = (
        "---\n"
        f"name: {name}\n"
        f"description: Horchestra member profile for the {profile.role} role. "
        "Session agent only (claude --agent); never invoke it as a subagent.\n"
        "---\n"
    )
    content = front + GENERATED_MARK.format(source=source) + "\n\n" + agent_body(profile, team_context)
    path = os.path.join(agents_dir, name + ".md")
    _write_if_changed(path, content)
    _remove_legacy_agent(agents_dir, name[len(AGENT_PREFIX):])
    return name


def _remove_legacy_agent(agents_dir, slug):
    """Delete the pre-0.1 `orchestra-<role>.md`, but only if we generated it."""
    path = os.path.join(agents_dir, LEGACY_PREFIX + slug + ".md")
    try:
        with open(path) as fh:
            generated = "<!-- generated by herdr-orchestra" in fh.read()
    except OSError:
        return
    if generated:
        os.remove(path)


def settings_for(profile):
    """Per-session settings, or None when nothing needs overriding."""
    settings = {}
    if profile.folder:
        # Load CLAUDE.md / rules from the --add-dir profile folder too.
        settings["env"] = {"CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD": "1"}
    if profile.all_denied:
        settings["permissions"] = {"deny": [f"Skill({p})" for p in profile.all_denied]}
    return settings or None


def write_settings(state_dir, key, profile):
    settings = settings_for(profile)
    if settings is None:
        return None
    folder = os.path.join(state_dir, "settings")
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, re.sub(r"[^A-Za-z0-9_.-]", "-", key) + ".json")
    _write_if_changed(path, json.dumps(settings, indent=2) + "\n")
    return path


def claude_args(team_root, state_dir, key, profile, team_context):
    """Launch args for a Claude member (before any user `args`)."""
    args = ["--agent", write_agent_file(team_root, profile, team_context)]
    settings = write_settings(state_dir, key, profile)
    if settings:
        args += ["--settings", settings]
    if profile.folder:
        args += ["--add-dir", profile.folder]  # variadic flag: keep it last
    return args


def _write_if_changed(path, content):
    try:
        with open(path) as fh:
            if fh.read() == content:
                return
    except OSError:
        pass
    tmp = path + ".tmp"
    with open(tmp, "w") as fh:
        fh.write(content)
    os.replace(tmp, path)
