import json
import os
import tempfile
import unittest
from unittest import mock

from tests import helpers  # noqa: F401
import roles


def make_role(root, name, text="Own the deck.", skills=()):
    folder = os.path.join(root, roles.ROLES_DIR, name)
    os.makedirs(folder)
    if text is not None:
        with open(os.path.join(folder, "ROLE.md"), "w") as fh:
            fh.write(text)
    for skill in skills:
        os.makedirs(os.path.join(folder, ".claude", "skills", skill))
        with open(os.path.join(folder, ".claude", "skills", skill, "SKILL.md"), "w") as fh:
            fh.write("---\nname: %s\ndescription: x\n---\n" % skill)
    return folder


class LoadTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = self.tmp.name

    def tearDown(self):
        self.tmp.cleanup()

    def test_role_folder_is_used_by_default(self):
        make_role(self.root, "slides", skills=["deck-style"])
        team = {"deny_skills": ["planner:*"]}
        profile = roles.load(self.root, team, {"role": "slides", "uses_skills": ["api-docs"],
                                               "deny_skills": ["video-*"]})
        self.assertEqual(profile.name, "slides")
        self.assertEqual(profile.text, "Own the deck.")
        self.assertEqual(profile.own_skills, ["deck-style"])
        self.assertEqual(profile.deny, ["planner:*", "video-*"])
        self.assertIn("1 own skill", profile.summary())

    def test_no_folder_means_no_profile(self):
        profile = roles.load(self.root, {}, {"role": "qa"})
        self.assertIsNone(profile.folder)
        self.assertTrue(profile.is_empty)
        self.assertIsNone(roles.settings_for(profile))

    def test_errors(self):
        with self.assertRaises(roles.RoleError):
            roles.load(self.root, {}, {"role": "qa", "profile": "missing"})
        with self.assertRaises(roles.RoleError):
            roles.load(self.root, {}, {"role": "qa", "profile": "../escape"})
        with self.assertRaises(roles.RoleError):
            roles.load(self.root, {}, {"role": "qa", "uses_skills": ["video-cli"],
                                       "deny_skills": ["video-*"]})


class LaunchTest(unittest.TestCase):
    def test_claude_args_write_agent_and_settings(self):
        with tempfile.TemporaryDirectory() as root, tempfile.TemporaryDirectory() as state:
            folder = make_role(root, "slides", text="Codeword TULIP.", skills=["deck-style"])
            profile = roles.load(root, {}, {"role": "slides", "uses_skills": ["api-docs"],
                                            "deny_skills": ["sql-helper"]})
            args = roles.claude_args(root, state, "proj-slides", profile, "You are on a team.")
            self.assertEqual(args[:2], ["--agent", "horchestra-slides"])
            self.assertEqual(args[-2:], ["--add-dir", folder])  # variadic flag last
            with open(os.path.join(root, ".claude", "agents", "horchestra-slides.md")) as fh:
                agent = fh.read()
            for expected in ("name: horchestra-slides", "Codeword TULIP.", "`api-docs`",
                             "`deck-style`", "`sql-helper`", "You are on a team."):
                self.assertIn(expected, agent)
            with open(args[args.index("--settings") + 1]) as fh:
                settings = json.load(fh)
            self.assertEqual(settings["permissions"]["deny"], ["Skill(sql-helper)"])
            self.assertEqual(settings["env"]["CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD"], "1")

    def test_refuses_to_overwrite_users_own_agent_file(self):
        with tempfile.TemporaryDirectory() as root:
            make_role(root, "slides")
            agents = os.path.join(root, ".claude", "agents")
            os.makedirs(agents)
            path = os.path.join(agents, "horchestra-slides.md")
            with open(path, "w") as fh:
                fh.write("---\nname: horchestra-slides\n---\nMy own agent.\n")
            profile = roles.load(root, {}, {"role": "slides"})
            with self.assertRaises(roles.RoleError) as ctx:
                roles.write_agent_file(root, profile, "ctx")
            self.assertIn("not generated by Horchestra", str(ctx.exception))
            with open(path) as fh:
                self.assertEqual(fh.read(), "---\nname: horchestra-slides\n---\nMy own agent.\n")

    def test_overwrites_our_generated_agent_file(self):
        with tempfile.TemporaryDirectory() as root:
            make_role(root, "slides", text="First.")
            profile = roles.load(root, {}, {"role": "slides"})
            roles.write_agent_file(root, profile, "ctx")
            role_md = os.path.join(root, roles.ROLES_DIR, "slides", "ROLE.md")
            with open(role_md, "w") as fh:
                fh.write("Second.")
            profile = roles.load(root, {}, {"role": "slides"})
            self.assertEqual(roles.write_agent_file(root, profile, "ctx"), "horchestra-slides")
            with open(os.path.join(root, ".claude", "agents", "horchestra-slides.md")) as fh:
                agent = fh.read()
            self.assertIn("Second.", agent)
            self.assertNotIn("First.", agent)

    def test_agent_names_are_safe(self):
        self.assertEqual(roles.agent_name("Research Lead!"), "horchestra-research-lead")


class OnlySkillsTest(unittest.TestCase):
    def test_allowlist_denies_everything_else_on_disk(self):
        with tempfile.TemporaryDirectory() as root, tempfile.TemporaryDirectory() as user, \
                tempfile.TemporaryDirectory() as state:
            for base, names in ((user, ["sql-helper", "chart-kit", "api-docs"]),
                                (os.path.join(root, ".claude", "skills"), ["lint-rules", "data-notes"])):
                for name in names:
                    os.makedirs(os.path.join(base, name))
                    with open(os.path.join(base, name, "SKILL.md"), "w") as fh:
                        fh.write("---\nname: %s\ndescription: x\n---\n" % name)
            make_role(root, "slides", skills=["deck-style"])
            member = {"role": "slides", "only_skills": ["api-docs", "lint-rules"]}
            profile = roles.load(root, {}, member, user_skills_dir=user)
            self.assertEqual(profile.allowed, ["api-docs", "lint-rules", "deck-style"])
            self.assertEqual(sorted(profile.auto_deny), ["chart-kit", "data-notes", "sql-helper"])
            self.assertIn("only 3 skills", profile.summary())
            body = roles.agent_body(profile, "ctx")
            self.assertIn("Use ONLY these skills", body)
            self.assertIn("`deck-style`", body)
            self.assertEqual(roles.settings_for(profile)["permissions"]["deny"],
                             ["Skill(chart-kit)", "Skill(sql-helper)", "Skill(data-notes)"])

    def test_allowlist_conflicting_with_deny_is_rejected(self):
        with tempfile.TemporaryDirectory() as root:
            with self.assertRaises(roles.RoleError):
                roles.load(root, {"deny_skills": ["api-*"]},
                           {"role": "slides", "only_skills": ["api-docs"]})

    def test_claude_config_dir_is_honored(self):
        with tempfile.TemporaryDirectory() as root, tempfile.TemporaryDirectory() as config:
            os.makedirs(os.path.join(config, "skills", "chart-kit"))
            with open(os.path.join(config, "skills", "chart-kit", "SKILL.md"), "w") as fh:
                fh.write("---\nname: chart-kit\ndescription: x\n---\n")
            with mock.patch.dict(os.environ, {"CLAUDE_CONFIG_DIR": config}):
                self.assertEqual(roles.claude_config_dir(), config)
                self.assertEqual(roles.discover_skills(root), ["chart-kit"])
            with mock.patch.dict(os.environ, {"CLAUDE_CONFIG_DIR": ""}):
                self.assertEqual(roles.claude_config_dir(), os.path.expanduser("~/.claude"))
            env = {k: v for k, v in os.environ.items() if k != "CLAUDE_CONFIG_DIR"}
            with mock.patch.dict(os.environ, env, clear=True):
                self.assertEqual(roles.claude_config_dir(), os.path.expanduser("~/.claude"))

    def test_frontmatter_name_wins_over_folder(self):
        with tempfile.TemporaryDirectory() as base:
            os.makedirs(os.path.join(base, "folder-name"))
            with open(os.path.join(base, "folder-name", "SKILL.md"), "w") as fh:
                fh.write('---\nname: "real-name"\ndescription: x\n---\n')
            self.assertEqual(roles.skill_name(os.path.join(base, "folder-name")), "real-name")


class BinaryAgentFileTest(unittest.TestCase):
    def test_non_text_user_file_is_refused_cleanly(self):
        with tempfile.TemporaryDirectory() as root:
            agents = os.path.join(root, ".claude", "agents")
            os.makedirs(agents)
            path = os.path.join(agents, roles.agent_name("slides") + ".md")
            with open(path, "wb") as fh:
                fh.write(b"\xff\xfe\x00 not utf-8")
            profile = roles.load(root, {}, {"role": "slides"})
            with self.assertRaises(roles.RoleError):
                roles.write_agent_file(root, profile, "ctx")
            with open(path, "rb") as fh:
                self.assertTrue(fh.read().startswith(b"\xff\xfe"))


if __name__ == "__main__":
    unittest.main()
